// ---------------------------------------------------------------------
// MIRRORS CANONICAL CONTRACTS 6.5 -- DO NOT EDIT THIS FILE.
// Canonical Contracts 0: if any other document disagrees, 6.5 wins.
// Canonical Contracts 10: frontend/src/types/ "must mirror 6.5".
// Agents: this file is off limits. If a field looks wrong, say so.
// Do not "fix" it. A change here is a contract change (REPOSITORY 7).
// ---------------------------------------------------------------------

export type SourceMode = "live_rtsp" | "live_hls" | "file" | "frames" | "synthetic";
export type MatchState = "exact" | "probable" | "low_confidence" | "unreadable";

export interface VehicleSighting {
  sighting_id: string;
  camera_id: string;
  camera_name: string;
  lat: number | null;
  lon: number | null;
  first_seen_at: string;
  last_seen_at: string;
  source_pts_ms: number | null;
  source_mode: SourceMode;
  plate: string | null;
  plate_raw: string | null;
  confidence: number | null;
  match_state: MatchState;
  evidence_count: number;
  plate_width_px: number | null;
  vehicle_type: string | null;
  snapshot_uri: string | null;
}

export interface JourneySegment {
  from_camera_id: string;
  to_camera_id: string;
  from_time: string;
  to_time: string;
  straight_line_km: number;
  elapsed_seconds: number;
  required_speed_kmh: number;
  feasible: boolean;
  note: string | null;
}

export interface JourneyResponse {
  plate: string;
  disclaimer: string;
  sighting_count: number;
  sightings: VehicleSighting[];
  segments: JourneySegment[];
}

export interface Alert {
  alert_id: string;
  plate: string;
  camera_id: string;
  camera_name: string;
  match_state: Exclude<MatchState, "low_confidence" | "unreadable">;
  confidence: number | null;
  priority: "low" | "medium" | "high" | "critical";
  created_at: string;
  acknowledged: boolean;
  snapshot_uri: string | null;
}

export interface SystemStatus {
  api: "ok" | "degraded";
  postgres: boolean;
  redis: boolean;
  source_mode: SourceMode;
  cameras_total: number;
  cameras_live: number;
  cameras_replay: number;
  is_live: boolean;
}